# Generated by Django 3.1.4 on 2021-05-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210512_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
