# Generated by Django 3.1.4 on 2021-05-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_deadline',
            field=models.DateField(null=True, verbose_name='Apply by'),
        ),
    ]
