# Generated by Django 3.1.4 on 2021-05-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210525_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_deadline',
            field=models.DateTimeField(null=True, verbose_name='Apply by'),
        ),
    ]
